<a href="https://colab.research.google.com/github/joaqxy/Linear-Algebra/blob/main/Assignment6_Jaymalin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Operation on Matrices 
Now that you have a fundamental knowledge about representing and operating with vectors as well as fudamentals of matrices, we'll try to the same operations with matrices and even more 

## Objectives 
At the end of this activity you will be able to: 

1. be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate eqautions. 
3. apply matrix algebra in engineering solutions. 

## Discussion 


In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition 

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

In [ ]:
A = np.array([
              [1,2,5],
              [5,-1,0],
              [0,-3,3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1


array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
## T method
AT2 = A.T
AT2


array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1,AT2)

True

In [ ]:
B = np.array([
              [1,2,3,4],
              [1,0,2,1],
])
B.shape 

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape 


(4, 2)

Try to create your own matrix 

In [ ]:
C = np.array([
              [3,2,0],
              [5,6,7],
              [8,1,10,]

])
C

array([[ 3,  2,  0],
       [ 5,  6,  7],
       [ 8,  1, 10]])

In [ ]:
C.shape

(3, 3)

In [ ]:
AT3 = C.T
AT3

array([[ 3,  5,  8],
       [ 2,  6,  1],
       [ 0,  7, 10]])

In [ ]:
C.T.shape 


(3, 3)

## Dot product / Inner product

In [3]:
X = np.array([
              [1,2],
              [0,1]
])
Y = np.array([
              [-1,0],
              [2,2]
])

In [4]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [5]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [6]:
X @ Y 


array([[3, 4],
       [2, 2]])

In [7]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In [8]:
J = np.array([
              [1,2,3],
              [0,1,4],
              [1,4,5]
])
J1 = np.array([
              [-1,0,6],
              [2,2,7],
              [5,6,8]
])

In [9]:
np.dot(J,J1)

array([[18, 22, 44],
       [22, 26, 39],
       [32, 38, 74]])

In [10]:
J.dot(J1)

array([[18, 22, 44],
       [22, 26, 39],
       [32, 38, 74]])

In [11]:
J @ J1

array([[18, 22, 44],
       [22, 26, 39],
       [32, 38, 74]])

In [12]:
np.matmul(J,J1)

array([[18, 22, 44],
       [22, 26, 39],
       [32, 38, 74]])

In [13]:
A = np.array([
              [2,4],
              [5,-2],
              [0,1]
])
B = np.array([
              [1,1],
              [3,3],
              [-1,-2]
])
C = np.array([
              [0,1,1],
              [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [14]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [15]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

In [16]:
X = np.array([
              [1,2,3,0]
])
Y = np.array([
              [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [17]:
X.T @ Y 

array([[ 1,  0,  4, -1],
       [ 2,  0,  8, -2],
       [ 3,  0, 12, -3],
       [ 0,  0,  0,  0]])

In [18]:
X @ Y.T

array([[13]])

In [19]:
A = np.array([
              [2,4,5],
              [5,-2,6],
              [0,1,4]
])
B = np.array([
              [1,1,2],
              [3,3,4],
              [-1,-2,6]
])
C = np.array([
              [0,1,1],
              [1,1,2],
              [8,5,1]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 3)
(3, 3)
(3, 3)


In [20]:
J = A @ (B + C)
J

array([[53, 35, 65],
       [39, 20, 45],
       [32, 16, 34]])

In [21]:
R = (A @ B ) + ( A @ C)
R

array([[53, 35, 65],
       [39, 20, 45],
       [32, 16, 34]])

In [22]:
np.array_equal(J,R)

True

In [23]:
A = np.array([
              [1,4],
              [0,3]
])
np.linalg.det(A)

3.0000000000000004

## Inverse
The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.



In [24]:
M = np.array([
              [1,7],
              [-3,5]
])
np.array(M @ np.linalg.inv(M), dtype = int)

array([[1, 0],
       [0, 1]])

In [30]:
A = np.array([
              [7, 8, 0],
              [5, 4, -3],
              [1, 2, 3]
])
B = np.linalg.inv(A)
B

array([[-1.        ,  1.33333333,  1.33333333],
       [ 1.        , -1.16666667, -1.16666667],
       [-0.33333333,  0.33333333,  0.66666667]])

In [31]:
A @ B

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.77555756e-16,  1.00000000e+00,  0.00000000e+00],
       [ 2.77555756e-16,  5.55111512e-17,  1.00000000e+00]])

In [33]:
J = np.array([
    [12,4,19,1,3,25,6],
    [3,5,10,15,6,4,3],
    [7,8,9,16,0,0,0],
    [1,6,3,5,8,32,11],
    [18,6,5,7,15,6,11],
    [-3,1,21,0,10,7,-35],
    [-1,-2,-3,26,22,10,12],
])
J_inv = np.linalg.inv(J)
np.array(J @ J_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [35]:
D = np.array([
    [1.0, 1.5, 0.5],
    [0.7, 0.5, 1.0],
    [1.5, 0.7, 0.3]
])
C = np.array([
    [0.2, 0.2, 0.6]
])
A_grade = D @ C.T
A_grade


array([[0.8 ],
       [0.84],
       [0.62]])

##Activity 


#Task 1
Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.




In [47]:
J = np.array([
          [1,2,3],
          [5,6,7],
          [9,1,2]
])
R = np.array([
          [2,4,6],
          [1,3,5],
          [1,3,2]
])

G = np.array([
          [1,5,6],
          [9,7,5],
          [8,6,4]
])

In [57]:
G.shape

(3, 3)

In [49]:
J1 = np.dot(J,R)
J1

array([[ 7, 19, 22],
       [23, 59, 74],
       [21, 45, 63]])

In [50]:
np.array_equiv(R,G)

False

In [52]:
A = J @ G
A

array([[ 43,  37,  28],
       [115, 109,  88],
       [ 34,  64,  67]])

In [54]:
B = J @ (R + G)
B

array([[ 50,  56,  50],
       [138, 168, 162],
       [ 55, 109, 130]])

In [56]:
C = R @ (G @ J)
C

array([[960, 672, 888],
       [717, 513, 678],
       [495, 345, 456]])

## Conclusion 
In conclusion, the objectives of the lab activity were achieved. The students were able to gain knowledge on performing different operations on matrices. This was achieved by practicing the different operations or codes on different kinds of matrices. Also it is important to consider the different characteristics of the matrices before operating on it. Sometimes, the code will have an error because the matrices are not compatible. 
