<a href="https://colab.research.google.com/github/joaqxy/Linear-Algebra/blob/main/Assignment_4_Jaymalin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE 
## Laboratory 4: Matrices

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$


$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

In [ ]:
## declaring a 2x2 matrix
#rank - how many rows are unique, not made of other rows
A = np.array([
              [1,2],
              [3,1]
])
describe_mat(A)

In [ ]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## declaring a row matrix
row_mat_1D = np.array([
                       1, 3, 2
]) ## this is a 1D matrix with a shape of (3,), it's not really considered as a row matrix
row_mat_2D = np.array([
                       [1,2,3]
])## this is a 2D matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

In [ ]:
## declaring a column matrix
col_mat = np.array([
                    [1],
                    [2],
                    [5]
])
describe_mat(col_mat)


### Square Matrices 
Matrices with same row and column sizes. 

In [3]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

##Null Matrix
A Null Matrix is a matrix that has no elements

In [7]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [8]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


## Zero Matrix 
A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [9]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


## Ones Matrix 
A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [10]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


## Diagonal Matrix 
A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [11]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [12]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]

False

##Identity Matrix
An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(5)

In [ ]:
np.identity(5)

##Upper Triangular Matrix
An upper triangular matrix is a matrix that has no values below the diagonal.

In [15]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

## Lower Triangular Matrix
A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

## Practice 

$$ A = \left\{\begin{array} 5x_1 + 2x_2 +x_3\\ 4x_2 - x_3\\ 10x_3 \end{array}\right. $$

Given the matrix below, express it as a linear combination in a markdown.

In [17]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [18]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

### Matrix Algebra 

### Addition 

In [19]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [20]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

### Subtraction

In [21]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [22]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

###Element-wise Multiplication

In [23]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [24]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [25]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [26]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

#Task 1


In [28]:
def mat_desc(matrix) :
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')
A = np.array([ 
[1, 2, 3], 
[4, 5, 6], 
[0, 2, 4] 
]) 
mat_desc(A)


Matrix:
[[1 2 3]
 [4 5 6]
 [0 2 4]]

Shape:	(3, 3)
Rank:	2



In [29]:
B = B = np.array([ 
[4, 5, 6], 
[9, 11, 2], 
[0, 14, 10] 
]) 
mat_desc(B) 


Matrix:
[[ 4  5  6]
 [ 9 11  2]
 [ 0 14 10]]

Shape:	(3, 3)
Rank:	2



In [53]:
def mat_desc(matrix): 
  if matrix.size > 0: 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {i} 
  else: 
print('Matrix is Null') 
C = np.array([]) 
mat_desc(C) 



SyntaxError: ignored

In [49]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((7,8)) 
zero_mat_rct = np.zeros((9,10)) 

print(f'Zero Row Matrix: \n{zero_mat_row}') 
print(f'Zero Square Matrix: \n{zero_mat_sqr}') 
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}') 


Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Zero Rectangular Matrix: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [50]:
ones_mat_row = np.ones((4,5)) 
ones_mat_sqr = np.ones((6,7)) 
ones_mat_rct = np.ones((8,9)) 

print(f'Ones Row Matrix: \n{ones_mat_row}') 
print(f'Ones square Matrix: \n{ones_mat_sqr}') 
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')


Ones Row Matrix: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Ones square Matrix: 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
Ones Rectangular Matrix: 
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [51]:
np.identity(8) 

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

#Task 2

In [61]:
A = np.array([ 
[3,2,3], 
[5,7,8], 
[9,0,1], 
[3,5,7] 
])

B = np.array([ 
[ 2,3,4],
[1,3,2], 
[5,7,9], 
[10,11,12] 
])

C = np.array([ 
[6,7,8], 
[3,4,2], 
[5,1,6] 
]) 


In [69]:
A + A




array([[ 6,  4,  6],
       [10, 14, 16],
       [18,  0,  2],
       [ 6, 10, 14]])

In [55]:
B + 2

array([[ 4,  5,  6],
       [ 3,  5,  4],
       [ 7,  9, 11],
       [12, 13, 14]])

In [65]:
B - A


array([[-1,  1,  1],
       [-4, -4, -6],
       [-4,  7,  8],
       [ 7,  6,  5]])

In [63]:
B*A

array([[ 6,  6, 12],
       [ 5, 21, 16],
       [45,  0,  9],
       [30, 55, 84]])

In [64]:
A/B

array([[1.5       , 0.66666667, 0.75      ],
       [5.        , 2.33333333, 4.        ],
       [1.8       , 0.        , 0.11111111],
       [0.3       , 0.45454545, 0.58333333]])

## Conclusion 
In summary, this lab activity taught the students how to display and analyze matrices. Through different exercises the students were able to perform and know different kinds of matrices. Besides from analyzing and displaying different kinds of matrices, the students were also able to perform different math operations with the matrices using different kinds of codes in Python. 
